# Generated by Django 3.2.15 on 2022-08-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='chatapp_message_thing1_or_thing2',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('chat_room_receiver__isnull', False), ('user_receiver__isnull', True)), models.Q(('chat_room_receiver__isnull', True), ('user_receiver__isnull', False)), _connector='OR'), name='chatapp_message_user_receiver_or_chat_room_receiver'),
        ),
    ]
