# Generated by Django 3.2.15 on 2022-08-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_auto_20220821_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chatroom',
            name='user_exit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user_chatroom',
            name='user_join_time',
            field=models.DateTimeField(null=True),
        ),
    ]
