# Generated by Django 3.2.15 on 2022-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_auto_20220821_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_chatroom',
            name='user_join_time',
            field=models.DateTimeField(),
        ),
    ]
